# Generated by Django 2.2.12 on 2022-02-11 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('first_name', models.CharField(max_length=110)),
                ('last_name', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=60, unique=True, verbose_name='email')),
                ('mobile', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=40)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
